FROM node:18-slim as builder

WORKDIR /app

COPY package*.json ./

RUN npm ci

COPY . ./

RUN npm run build

# Run
FROM node:18-slim as worknode

ENV NODE_ENV=production

WORKDIR /app

COPY --from=builder /app/build ./

COPY package*.json ./

RUN npm ci

CMD ["node", "index.js"]
